In [1]:
import numpy as np

In [3]:
X=np.array([[2,10],[2,5],[8,4],[5,8],[7,5],[6,4],[1,2],[4,9]])

In [30]:
c=np.zeros([3,2])
c[0]=X[0]
c[1]=X[3]
c[2]=X[6]

In [31]:
for i in range(10):
    c1=[]
    c2=[]
    c3=[]

    for x in X:
        # 计算到每个中心的距离
        dis=np.sum((x-c)**2,axis=1)
        # print(np.sum((x-c)**2,axis=1))
        minSite=np.argmin(dis)
        # print(minSite)
        if minSite==0:
            c1.append(x)
        elif minSite==1:
            c2.append(x)
        else:
            c3.append(x)
    c1=np.asarray(c1)
    print(c1)
    c2=np.asarray(c2)
    print(c2)
    c3=np.asarray(c3)
    print(c3)
    # 计算新的中心
    c[0]=c1.mean(axis=0)
    c[1]=c2.mean(axis=0)
    c[2]=c3.mean(axis=0)
    print(c)
        

[[ 2 10]]
[[8 4]
 [5 8]
 [7 5]
 [6 4]
 [4 9]]
[[2 5]
 [1 2]]
[[ 2.  10. ]
 [ 6.   6. ]
 [ 1.5  3.5]]
[[ 2 10]
 [ 4  9]]
[[8 4]
 [5 8]
 [7 5]
 [6 4]]
[[2 5]
 [1 2]]
[[3.   9.5 ]
 [6.5  5.25]
 [1.5  3.5 ]]
[[ 2 10]
 [ 5  8]
 [ 4  9]]
[[8 4]
 [7 5]
 [6 4]]
[[2 5]
 [1 2]]
[[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]
[[ 2 10]
 [ 5  8]
 [ 4  9]]
[[8 4]
 [7 5]
 [6 4]]
[[2 5]
 [1 2]]
[[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]
[[ 2 10]
 [ 5  8]
 [ 4  9]]
[[8 4]
 [7 5]
 [6 4]]
[[2 5]
 [1 2]]
[[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]
[[ 2 10]
 [ 5  8]
 [ 4  9]]
[[8 4]
 [7 5]
 [6 4]]
[[2 5]
 [1 2]]
[[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]
[[ 2 10]
 [ 5  8]
 [ 4  9]]
[[8 4]
 [7 5]
 [6 4]]
[[2 5]
 [1 2]]
[[3.66666667 9.        ]
 [7.         4.33333333]
 [1.5        3.5       ]]
[[ 2 10]
 [ 5  8]
 [ 4  9]]
[[8 4]
 [7 5]
 [6 4]]
[[2 5]
 [1 2]]
[[3.66666667 9.        ]
 

In [17]:
c1.mean(axis=0)

array([ 2., 10.])

In [19]:
c

array([[ 2. , 10. ],
       [ 6. ,  6. ],
       [ 1.5,  3.5]])