author: leezeeyee   
date: 2021/4/13  
link: [github](https://github.com/easilylazy/pattern-recognition) 

In [1]:
import pandas as pd
import numpy as np

In [2]:
irisData=pd.read_csv('iris.csv')
irisData.head()

Unnamed: 0  Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           1           5.1          3.5           1.4          0.2  setosa
1           2           4.9          3.0           1.4          0.2  setosa
2           3           4.7          3.2           1.3          0.2  setosa
3           4           4.6          3.1           1.5          0.2  setosa
4           5           5.0          3.6           1.4          0.2  setosa

In [3]:
## different types
setosas=irisData[irisData['Species']=='setosa']
versicolors=irisData[irisData['Species']=='versicolor']
virginicas=irisData[irisData['Species']=='virginica']

In [4]:
classes=3
Y=np.r_[np.zeros(len(setosas),dtype=int),np.ones(len(versicolors), dtype=int),2*np.ones(len(virginicas), dtype=int)]
one_hot_Y = np.eye(classes)[Y]


In [5]:
X=np.asarray(irisData[['Sepal.Length',	'Sepal.Width',	'Petal.Length',	'Petal.Width']].iloc[:,:])

In [6]:
trainX=[]
trainY=[]
testX=[]
testY=[]

for i in range(classes):
    index=np.where(Y==i)[0]
    np.random.shuffle(index)
    
    trainX.append(X[index[:30]])
    testX.append(X[index[30:]])
    trainY.append(one_hot_Y[index[:30]])
    testY.append(one_hot_Y[index[30:]])
    print(index)
print(trainX[2][0])
print(X[index[0]])
trainX_sh=np.r_[trainX[0],trainX[1],trainX[2]]
trainY_sh=np.r_[trainY[0],trainY[1],trainY[2]]
testX_sh=np.r_[testX[0],testX[1],testX[2]]
testY_sh=np.r_[testY[0],testY[1],testY[2]]
trainX_sh[:3]

[49 19  9  5 41  3  8 33 45 28 35 36 38  2 39 44 48 16 34 43 14 23 17 29
  0 26 22 11 24 10 32  7 21 20 40 27 42 30 46 13 37 18 12  4 25 31  6 15
  1 47]
[50 95 92 98 79 94 63 69 75 62 67 85 74 78 89 54 90 73 57 61 81 97 91 77
 66 87 83 70 93 59 58 84 72 99 60 82 64 52 65 53 71 55 56 68 86 88 80 76
 96 51]
[131 132 123 121 142 107 105 106 133 103 130 149 104 137 117 115 102 146
 125 100 139 110 134 111 145 122 129 108 114 101 138 148 143 124 128 135
 127 109 118 119 140 116 141 120 144 136 112 126 113 147]
[7.9 3.8 6.4 2. ]
[7.9 3.8 6.4 2. ]


array([[5. , 3.3, 1.4, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [4.9, 3.1, 1.5, 0.1]])

In [40]:
def softmax(X,Y,maxStep=120,stepSize=1):
    ## param
    # k for class num; N for dimension of data
    K=3
    N=4
    W=np.zeros([K,N])
    # M for the item num of data
    M=len(X)
    ## compute si
    softMaxY=np.zeros(K)
    # initialize W
    W=np.zeros([K,N])
    # record best W
    errMin=M
    for step in range(120):
        for i in range(M):
            # print(np.dot(W,np.transpose(X[i])))
            S=np.dot(W,np.transpose(X[i]))
            # print(np.dot(S,np.transpose(Y[i])))
            
            # print(np.where(y==1)[0][0]==np.where(S==np.max(S))[0][0])
            softMaxS=np.exp(S)
            sumY=np.sum(softMaxS)
            # print(sumY)
            # print(softMaxY)
            for j in range(K):
                softMaxY[j]=softMaxS[j]/sumY
                if Y[i][j]==1:
                    W[j]-=stepSize*(softMaxY[j]-1)*X[i]
                else:
                    W[j]-=stepSize*(softMaxY[j])*X[i]
            # print(step)
            # print(softMaxY)
            # print(W)

        Pass=True
        err=0
        for i in range(len(X)):
            y=Y[i]
            S=np.dot(W,np.transpose(X[i]))
            if np.where(y==1)[0][0] != np.where(S==np.max(S))[0][0]:
                err+=1
                Pass=False
        if Pass is True:
            print('success')
            break
        else:
            pass
        if err<errMin:
            W_end=W
            errMin=err
            print('err: '+str(err))
    return W_end

In [42]:
W_end=softmax(X=trainX_sh,Y=trainY_sh,maxStep=200)

err: 60
err: 30
err: 28
err: 26
err: 21
err: 18
err: 16
err: 14
err: 13
err: 12
err: 8
err: 7
err: 4


In [43]:
W_end

array([[ 15.81112834,  26.75092144, -39.79101032, -16.21367521],
       [ 28.65801652, -15.79952856, -27.27798885, -13.73633682],
       [-44.46914485, -10.95139287,  67.06899917,  29.95001202]])

In [33]:
type(Y[0])

numpy.int32

In [7]:
targets 

array([2, 3, 4, 0])

In [23]:
type(targets[0])

numpy.int32

In [59]:
# k for class num; N for dimension of data
K=3
N=4
W=np.zeros([K,N])
# M for the item num of data
M=4

## test

In [44]:
X=testX_sh
Y=testY_sh
err=0
for i in range(len(X)):
            y=Y[i]
            S=np.dot(W_end,np.transpose(X[i]))
            if np.where(y==1)[0][0] != np.where(S==np.max(S))[0][0]:
                print(y)
                print(S)
                err+=1
print(err)

[0. 1. 0.]
[-2.21853060e+01 -1.17104195e-02  2.21970165e+01]
[0. 1. 0.]
[-37.74720192 -36.00075157  73.74795349]
[0. 1. 0.]
[-52.80905126 -13.21996797  66.02901923]
[0. 1. 0.]
[-19.19490853 -10.584978    29.77988653]
[0. 1. 0.]
[-22.92472676   2.48172765  20.44299912]
[0. 1. 0.]
[-10.70931826   0.69000796  10.0193103 ]
[0. 1. 0.]
[ 1.79457594 -1.39173808 -0.40283786]
[0. 1. 0.]
[-27.27182139  -5.5048752   32.77669659]
[0. 1. 0.]
[-8.91717438  3.77614961  5.14102477]
[0. 1. 0.]
[-31.75349389  -5.68901814  37.44251202]
[0. 1. 0.]
[-8.89135616  3.60602749  5.28532867]
[0. 1. 0.]
[-35.11131266 -21.49617354  56.6074862 ]
[0. 1. 0.]
[-25.07147956 -21.77762673  46.84910629]
[0. 1. 0.]
[-46.49903639  -0.43471551  46.9337519 ]
[0. 1. 0.]
[-22.475845    -5.78088073  28.25672573]
[0. 1. 0.]
[-15.42583708 -16.61068536  32.03652244]
[0. 1. 0.]
[-17.87746464   0.93389414  16.9435705 ]
[0. 1. 0.]
[-31.2777421    0.47061429  30.80712782]
[0. 1. 0.]
[-20.49891742 -14.89272974  35.39164716]
[0. 1. 0.]
[

In [12]:
X[i]

array([4.7, 3.2, 1.3, 0.2])

In [13]:
testX_sh[i]

array([5.1, 3.7, 1.5, 0.4])

In [20]:
print(len(X))

60
