In [2]:
## softmax


In [3]:
import numpy as np

In [10]:
# k for class num; N for dimension of data
K=3
N=3
W=np.zeros([K,N])

In [5]:
# M for the item num of data
M=4
X=np.array([
    [1,3,0],
    [1,3,6],
    [1,0,3],
    [1,-3,0],
])
Y=np.array([
    [1,0,0],
    [1,0,0],
    [0,1,0],
    [0,0,1],
])


In [31]:
y=Y[3]
y[y[y==1]]
np.where(y==1)[0][0]
np.where(y==np.max(y))[0][0]

2

In [45]:
## compute si
softMaxY=np.zeros(K)
# step size
stepSize=1
# initialize W
W=np.zeros([K,N])
for step in range(30):
    Pass=True
    for i in range(M):
        # print(np.dot(W,np.transpose(X[i])))
        S=np.dot(W,np.transpose(X[i]))
        # print(S)
        # print(np.dot(S,np.transpose(Y[i])))
        y=Y[i]
        if np.where(y==1)[0][0] != np.where(S==np.max(S))[0][0]:
            Pass=False
        # print(np.where(y==1)[0][0]==np.where(S==np.max(S))[0][0])
        softMaxS=np.exp(S)
        sumY=np.sum(softMaxS)
        # print(sumY)
        # print(softMaxY)
        for j in range(K):
            softMaxY[j]=softMaxS[j]/sumY
            if Y[i][j]==1:
                W[j]-=stepSize*(softMaxY[j]-1)*X[i]
            else:
                W[j]-=stepSize*(softMaxY[j])*X[i]
    print(step)
    print(W)
    if Pass is True:
        print('success')
        break
    

0
[[ 0.08994625  2.00046003 -1.72970123]
 [-0.27601725  1.19290236  2.36485061]
 [ 0.186071   -3.19336239 -0.63514939]]
1
[[ 0.14788791  5.17428453  1.27029923]
 [-0.34936638 -1.93469819 -0.63514938]
 [ 0.20147848 -3.23958635 -0.63514985]]
2
[[-0.84666696  5.17428454 -1.71336536]
 [ 0.61828979 -1.84364005  2.35887727]
 [ 0.22837717 -3.33064449 -0.64551191]]
3
[[-0.85447549  8.15085755  1.23978205]
 [-0.36625924 -1.84313898 -0.59426873]
 [ 1.22073473 -6.30771856 -0.64551332]]
4
[[-1.82112458  8.15085755 -1.66016524]
 [ 0.6273168  -1.84313639  2.386462  ]
 [ 1.19380778 -6.30772116 -0.72629676]]
5
[[-1.78393507  8.26243176 -1.43702251]
 [ 0.59044033 -1.9547071   2.16426188]
 [ 1.19349474 -6.30772466 -0.72723937]]
success
