In [1]:
## softmax


In [2]:
import numpy as np

In [3]:
# k for class num; N for dimension of data
K=3
N=3
W=np.zeros([K,N])

In [4]:
# M for the item num of data
M=4
X=np.array([
    [1,3,0],
    [1,3,6],
    [1,0,3],
    [1,-3,0],
])
Y=np.array([
    [1,0,0],
    [1,0,0],
    [0,1,0],
    [0,0,1],
])


In [5]:
y=Y[3]
y[y[y==1]]
np.where(y==1)[0][0]
np.where(y==np.max(y))[0][0]

2

In [44]:
## compute si
softMaxY=np.zeros(K)
# step size
stepSize=1
# initialize W
W=np.zeros([K,N])
for step in range(5):
    S=np.dot(X,np.transpose(W))
    softMaxS=np.exp(S)
    print('S')
    print(S)
    # print('softMaxS')
    # print(softMaxS)

    softMaxY=softMaxS/(np.sum(softMaxS,axis=1)[:, np.newaxis])
    # print(np.sum(softMaxS,axis=1))
    deltaE=np.dot(np.transpose(softMaxY-Y),X)
    print('deltaE')
    print(deltaE)
    W-=stepSize*deltaE
    print('W')
    print(W)
    Pass=True
    for i in range(M):
        y=Y[i]
        S=np.dot(W,np.transpose(X[i]))
        if np.where(y==1)[0][0] != np.where(S==np.max(S))[0][0]:
            Pass=False
    if Pass is True:
        print('success')
        break
    

S
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
deltaE
[[-6.66666667e-01 -5.00000000e+00 -3.00000000e+00]
 [ 3.33333333e-01  1.00000000e+00 -2.22044605e-16]
 [ 3.33333333e-01  4.00000000e+00  3.00000000e+00]]
W
[[ 6.66666667e-01  5.00000000e+00  3.00000000e+00]
 [-3.33333333e-01 -1.00000000e+00  2.22044605e-16]
 [-3.33333333e-01 -4.00000000e+00 -3.00000000e+00]]
S
[[ 15.66666667  -3.33333333 -12.33333333]
 [ 33.66666667  -3.33333333 -30.33333333]
 [  9.66666667  -0.33333333  -9.33333333]
 [-14.33333333   2.66666667  11.66666667]]
deltaE
[[ 9.99954591e-01 -1.68257894e-08  2.99986379e+00]
 [-9.99831202e-01 -3.70166920e-04 -2.99986381e+00]
 [-1.23388978e-04  3.70183745e-04  1.68076262e-08]]
W
[[-3.33287924e-01  5.00000002e+00  1.36210413e-04]
 [ 6.66497869e-01 -9.99629833e-01  2.99986381e+00]
 [-3.33209944e-01 -4.00037018e+00 -3.00000002e+00]]
S
[[ 14.66671213  -2.33239163 -12.3343205 ]
 [ 14.66752939  15.66679121 -30.3343206 ]
 [ -0.33287929   9.66608929  -9.33320999]
 [-15.33328797  

In [59]:
Wbest=np.asarray([[-1.82112458,  8.15085755, -1.66016524],
 [ 0.6273168,  -1.84313639,  2.386462  ],
 [ 1.19380778, -6.30772116, -0.72629676]])

In [61]:
for i in range(M):
        # print(np.dot(W,np.transpose(X[i])))
        Sbest=np.dot(Wbest,np.transpose(X[i]))
        print(Sbest)

[ 22.63144807  -4.90209237 -17.7293557 ]
[ 12.67045663   9.41667963 -22.08713626]
[-6.8016203  7.7867028 -0.9850825]
[-26.27369723   6.15672597  20.11697126]
