In [2]:
## softmax


In [3]:
import numpy as np

In [10]:
# k for class num; N for dimension of data
K=3
N=3
W=np.zeros([K,N])

In [47]:
# M for the item num of data
M=4
X=np.array([
    [1,3,0],
    [1,3,6],
    [1,0,3],
    [1,-3,0],
])
Y=np.array([
    [1,0,0],
    [1,0,0],
    [0,1,0],
    [0,0,1],
])


In [48]:
y=Y[3]
y[y[y==1]]
np.where(y==1)[0][0]
np.where(y==np.max(y))[0][0]

2

In [57]:
## compute si
softMaxY=np.zeros(K)
# step size
stepSize=1
# initialize W
W=np.zeros([K,N])
for step in range(30):
    for i in range(M):
        # print(np.dot(W,np.transpose(X[i])))
        S=np.dot(W,np.transpose(X[i]))
        # print(S)
        # print(np.dot(S,np.transpose(Y[i])))
        
        # print(np.where(y==1)[0][0]==np.where(S==np.max(S))[0][0])
        softMaxS=np.exp(S)
        sumY=np.sum(softMaxS)
        # print(sumY)
        # print(softMaxY)
        for j in range(K):
            softMaxY[j]=softMaxS[j]/sumY
            if Y[i][j]==1:
                W[j]-=stepSize*(softMaxY[j]-1)*X[i]
            else:
                W[j]-=stepSize*(softMaxY[j])*X[i]
        print(step)
        print(softMaxY)
        print(W)

    Pass=True
    for i in range(M):
        y=Y[i]
        S=np.dot(W,np.transpose(X[i]))
        if np.where(y==1)[0][0] != np.where(S==np.max(S))[0][0]:
            Pass=False
    if Pass is True:
        print('success')
        break
    

0
[0.33333333 0.33333333 0.33333333]
[[ 0.66666667  2.          0.        ]
 [-0.33333333 -1.          0.        ]
 [-0.33333333 -1.          0.        ]]
0
[9.99909208e-01 4.53958078e-05 4.53958078e-05]
[[ 6.66757458e-01  2.00027237e+00  5.44749694e-04]
 [-3.33378729e-01 -1.00013619e+00 -2.72374847e-04]
 [-3.33378729e-01 -1.00013619e+00 -2.72374847e-04]]
0
[0.57674866 0.21162567 0.21162567]
[[ 0.0900088   2.00027237 -1.72970123]
 [ 0.4549956  -1.00013619  2.36485061]
 [-0.5450044  -1.00013619 -0.63514939]]
0
[6.25504750e-05 7.31012851e-01 2.68924599e-01]
[[ 0.08994625  2.00046003 -1.72970123]
 [-0.27601725  1.19290236  2.36485061]
 [ 0.186071   -3.19336239 -0.63514939]]
1
[9.42058496e-01 5.79413264e-02 1.77369554e-07]
[[ 0.14788775  2.17428454 -1.72970123]
 [-0.33395858  1.01907839  2.36485061]
 [ 0.18607082 -3.19336292 -0.63514939]]
1
[1.10895662e-09 9.99999999e-01 8.32195146e-14]
[[ 1.14788775  5.17428453  4.27029877]
 [-1.33395858 -1.98092161 -3.63514938]
 [ 0.18607082 -3.19336292 

In [59]:
Wbest=np.asarray([[-1.82112458,  8.15085755, -1.66016524],
 [ 0.6273168,  -1.84313639,  2.386462  ],
 [ 1.19380778, -6.30772116, -0.72629676]])

In [61]:
for i in range(M):
        # print(np.dot(W,np.transpose(X[i])))
        Sbest=np.dot(Wbest,np.transpose(X[i]))
        print(Sbest)

[ 22.63144807  -4.90209237 -17.7293557 ]
[ 12.67045663   9.41667963 -22.08713626]
[-6.8016203  7.7867028 -0.9850825]
[-26.27369723   6.15672597  20.11697126]
