author: leezeeyee   
date: 2021/4/12  
link: [github](https://github.com/easilylazy/pattern-recognition) 

## 梯度下降法 求取SVM



$$ERR_{SVM}=max(0,1-y_s)$$
$$y_s=y_n(W^{T}X_n+b)$$
$$\frac{\partial(1-y_s)}{\partial W_i}=-y_nX_i$$
$$\frac{\partial(1-y_s)}{\partial W}=-y_nX$$
$$$$
$$$$

In [1]:
import numpy as np

In [2]:
D=np.asarray([[1,1],[2,2],[2,0],[0,0],[1,0],[0,1]])
Y=np.asarray([1,1,1,-1,-1,-1])

In [4]:
def addSingleBias(X):
    N=X.shape[0]
    X=np.reshape(X,[N,1])
    bias_vector=np.ones([1,1])
    return np.row_stack((bias_vector,X))
def addBias(X):
    '''
    为维数为N,d的向量X添加偏置向量
    Args:
        X(numpy.ndarray):shape为[N,d]
    Returns:
        numpy.ndarray:shape为[N,d+1]，且第一列列向量全为1
    '''
    
    try:
        N=X.shape[0]
        d=X.shape[1]
        if d == 1:
            return addSingleBias(X)
        bias_vector=np.ones([N,1])
        return np.column_stack((bias_vector,X))
        
    except:
        return addSingleBias(X)

In [5]:
addBias(D)

array([[1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 0.],
       [1., 0., 0.],
       [1., 1., 0.],
       [1., 0., 1.]])

## 最佳边界
直到导数为0停止

In [ ]:
W=np.zeros([3,1])
learning_rate=0.1

## 分离即退出
非最佳边界

In [22]:
W=np.zeros([3,1])
learning_rate=0.1

In [37]:
for iteration in range(100):
    Pass=True
    for i in range(len(D)):
        X=addBias(D[i])
        yn=Y[i]
        Err=1-yn*np.dot(W.transpose(),X)
        if Err>0:
            Pass=False
            dErr_dW=-yn*X
            W-=learning_rate*dErr_dW
        # print(W)
            print(Err)
    if Pass is True:
        print('success')
        print(W)
        break

success
[[-3.2]
 [ 2.2]
 [ 2.2]]


## validation

In [31]:
Wt=np.asarray([[-3.2],
 [ 2.2],
 [ 2.2]])

In [34]:
for i in range(len(D)):
        X=addBias(D[i])
        yn=Y[i]
        Err=1-yn*np.dot(Wt.transpose(),X)
        dErr_dW=-yn*X
        print(dErr_dW)
        if Err>0:
            print('false')
            break
            # dErr_dW=-yn*X
            # W-=learning_rate*dErr_dW
        # print(W)
        # print(Err)

[[-1.]
 [-1.]
 [-1.]]
[[-1.]
 [-2.]
 [-2.]]
[[-1.]
 [-2.]
 [-0.]]
[[1.]
 [0.]
 [0.]]
[[1.]
 [1.]
 [0.]]
[[1.]
 [0.]
 [1.]]
