In [1]:
from cifar10 import CIFAR10
import numpy as np
import torch
from torchvision import transforms

In [2]:
np.random.seed(0)

In [3]:
batch_size=1
fake_data=np.random.randint(0,255,size=(batch_size,3*32*32))
fake_targets=np.random.randint(0,10,size=(batch_size,1))

In [4]:
transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.247, 0.243, 0.261)),
])

In [31]:
testset = CIFAR10(
    root='./data',data=fake_data,targets=fake_targets, train=False, download=True, transform=transform_test)
test_dataloader = torch.utils.data.DataLoader(
    testset, batch_size=100, shuffle=False, num_workers=2)

NameError: name 'CIFAR10' is not defined

In [6]:
testset.data.shape

(1, 32, 32, 3)

In [ ]:

trainset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True, transform=transform_train)
train_dataloader = torch.utils.data.DataLoader(
    trainset, batch_size=128, shuffle=False, num_workers=2)

In [29]:
from input_data import  load_data

In [36]:
path='data/cifar-10-batches-py'
data_sets=load_data(path=path,augment=True,raw=False)

load raw data...


In [37]:
import torchvision
import torch
from torchvision import transforms

In [6]:
torch.manual_seed(0)

In [38]:
transform_train = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomCrop(32, padding=4),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.247, 0.243, 0.261)),
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.247, 0.243, 0.261)),
])

path='data/cifar-10-batches-py'
data_sets=load_data(path=path,augment=True,raw=False)

In [39]:

trainset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True)#, transform=transform_train)
train_dataloader = torch.utils.data.DataLoader(
    trainset, batch_size=128, shuffle=False, num_workers=2)

testset = torchvision.datasets.CIFAR10(
    root='./data', train=False, download=True, transform=transform_test)
test_dataloader = torch.utils.data.DataLoader(
    testset, batch_size=100, shuffle=False, num_workers=2)

Files already downloaded and verified
Files already downloaded and verified


In [40]:
trainset.data

(50000, 32, 32, 3)

In [41]:
import numpy as np

In [48]:
np.mean(trainset.data.reshape(50000*32*32,3),axis=0)

array([125.30691805, 122.95039414, 113.86538318])

In [49]:
np.array([125.30691805, 122.95039414, 113.86538318])/255

array([0.49139968, 0.48215841, 0.44653091])

In [50]:
np.std(trainset.data.reshape(50000*32*32,3),axis=0)

array([62.99321928, 62.08870764, 66.70489964])

In [51]:
np.array([62.99321928, 62.08870764, 66.70489964])/255

array([0.24703223, 0.24348513, 0.26158784])

In [23]:
_, pred = torch.topk(maxk, 1, True, True)


128

In [24]:
for X,y in train_dataloader:
    sysX,sysY=X,y
    break
for X,y in test_dataloader:
    sysXt,sysYt=X,y
    print(1)
    break

1


In [25]:
sysX.shape

torch.Size([128, 3, 32, 32])

In [40]:
from torch.utils.data import DataLoader
batch_size=128
train_dataloader = DataLoader(data_sets.train, batch_size=batch_size, shuffle=False)
test_dataloader = DataLoader(data_sets.test, batch_size=100, shuffle=False)


In [41]:
for X,y in train_dataloader:
    ownX,ownY=X,y
    print(1)
    break
for X,y in test_dataloader:
    ownXt,ownYt=X,y
    print(1)
    break

1
1


In [42]:
print(ownY-sysY)


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])


In [43]:
((ownX-sysX)/ownX*100).type(torch.int)

tensor([[[[   104,    109,    106,  ...,    -22,    -22,    -22],
          [   183,    123,    115,  ...,   -130,    -22,    -22],
          [ -1874,    390,    184,  ...,    -39,    -22,    -22],
          ...,
          [   420,    352,  -1253,  ...,    261,    -22,    -22],
          [   540,   1408,   -103,  ...,    285,    -22,    -22],
          [   360,   2787,    -67,  ...,    379,    -22,    -22]],

         [[    67,     70,     67,  ...,    -21,    -21,    -21],
          [   854,    861,    987,  ...,   -145,    -21,    -21],
          [  -140,   -148,    -80,  ...,    -45,    -21,    -21],
          ...,
          [   812,    567,   -316,  ...,    353,    -21,    -21],
          [  1592,   -734,    -51,  ...,    418,    -21,    -21],
          [   698,   -417,    -27,  ...,   1034,    -21,    -21]],

         [[    27,     28,     26,  ...,    -29,    -29,    -29],
          [ -1714,   -872,   -697,  ...,   -190,    -29,    -29],
          [   -98,    -92,    -60,  ...,  

In [44]:
print(ownX-sysX)

tensor([[[[-2.0804e+00, -2.1774e+00, -2.1192e+00,  ...,  4.3959e-01,
            4.3959e-01,  4.3959e-01],
          [ 9.5148e-01,  6.4132e-01,  6.1843e-01,  ...,  1.3763e+00,
            4.3959e-01,  4.3959e-01],
          [ 6.8657e-01,  4.7702e-01,  2.2502e-01,  ...,  6.9362e-01,
            4.3959e-01,  4.3959e-01],
          ...,
          [ 3.1863e+00,  3.3927e+00,  2.2495e+00,  ...,  3.9325e+00,
            4.3959e-01,  4.3959e-01],
          [ 2.9799e+00,  2.6147e+00,  1.2334e+00,  ...,  3.7420e+00,
            4.3959e-01,  4.3959e-01],
          [ 3.3609e+00,  2.5195e+00,  9.7940e-01,  ...,  3.2974e+00,
            4.3959e-01,  4.3959e-01]],

         [[-1.3361e+00, -1.3951e+00, -1.3361e+00,  ...,  4.3389e-01,
            4.3389e-01,  4.3389e-01],
          [ 1.2464e+00,  9.7817e-01,  9.6203e-01,  ...,  1.4345e+00,
            4.3389e-01,  4.3389e-01],
          [ 7.9204e-01,  6.4581e-01,  3.7753e-01,  ...,  7.5666e-01,
            4.3389e-01,  4.3389e-01],
          ...,
     

In [45]:
print(ownXt-sysXt)


tensor([[[[-0.1147, -0.1182, -0.1392,  ..., -0.0410, -0.0024,  0.0327],
          [-0.0936, -0.0901, -0.1182,  ..., -0.0375,  0.0011,  0.0221],
          [-0.0901, -0.0901, -0.1147,  ..., -0.0480, -0.0165,  0.0186],
          ...,
          [ 0.2010,  0.2923,  0.3308,  ...,  0.3063,  0.3940,  0.2993],
          [ 0.2256,  0.2677,  0.3168,  ...,  0.3484,  0.3379,  0.3694],
          [ 0.2502,  0.2431,  0.2817,  ...,  0.3554,  0.3203,  0.3659]],

         [[ 0.0387,  0.0422,  0.0246,  ...,  0.0987,  0.1128,  0.1340],
          [ 0.0387,  0.0457,  0.0316,  ...,  0.0987,  0.1128,  0.1234],
          [ 0.0457,  0.0493,  0.0422,  ...,  0.0881,  0.0987,  0.1198],
          ...,
          [-0.0037,  0.0810,  0.1234,  ...,  0.0916,  0.2081,  0.1340],
          [ 0.0246,  0.0740,  0.1340,  ...,  0.1445,  0.1445,  0.2081],
          [ 0.0563,  0.0634,  0.1198,  ...,  0.1622,  0.1375,  0.1975]],

         [[ 0.2909,  0.2999,  0.2819,  ...,  0.3492,  0.3492,  0.3627],
          [ 0.2819,  0.3313,  

In [46]:
trainset.data.shape

(50000, 32, 32, 3)

In [47]:
data_sets.train.images.shape

torch.Size([50000, 3, 32, 32])

In [48]:
mine=data_sets.train.images
sys=trainset.data.transpose(0,3,1,2)

In [49]:
sys[0]

array([[[ 59,  43,  50, ..., 158, 152, 148],
        [ 16,   0,  18, ..., 123, 119, 122],
        [ 25,  16,  49, ..., 118, 120, 109],
        ...,
        [208, 201, 198, ..., 160,  56,  53],
        [180, 173, 186, ..., 184,  97,  83],
        [177, 168, 179, ..., 216, 151, 123]],

       [[ 62,  46,  48, ..., 132, 125, 124],
        [ 20,   0,   8, ...,  88,  83,  87],
        [ 24,   7,  27, ...,  84,  84,  73],
        ...,
        [170, 153, 161, ..., 133,  31,  34],
        [139, 123, 144, ..., 148,  62,  53],
        [144, 129, 142, ..., 184, 118,  92]],

       [[ 63,  45,  43, ..., 108, 102, 103],
        [ 20,   0,   0, ...,  55,  50,  57],
        [ 21,   0,   8, ...,  50,  50,  42],
        ...,
        [ 96,  34,  26, ...,  70,   7,  20],
        [ 96,  42,  30, ...,  94,  34,  34],
        [116,  94,  87, ..., 140,  84,  72]]], dtype=uint8)

In [50]:
mine[0]

tensor([[[-1.9895, -1.9895, -1.9895,  ..., -1.9895, -1.9895, -1.9895],
         [ 0.5191,  0.5191,  0.5349,  ..., -1.0527, -1.9895, -1.9895],
         [-0.0366,  0.1221,  0.1221,  ..., -1.7354, -1.9895, -1.9895],
         ...,
         [ 0.7572,  0.9636, -0.1795,  ...,  1.5034, -1.9895, -1.9895],
         [ 0.5508,  0.1856, -1.1956,  ...,  1.3129, -1.9895, -1.9895],
         [ 0.9319,  0.0904, -1.4497,  ...,  0.8683, -1.9895, -1.9895]],

        [[-1.9844, -1.9844, -1.9844,  ..., -1.9844, -1.9844, -1.9844],
         [ 0.1459,  0.1136,  0.0975,  ..., -0.9838, -1.9844, -1.9844],
         [-0.5642, -0.4351, -0.4674,  ..., -1.6616, -1.9844, -1.9844],
         ...,
         [ 0.3395,  0.5171, -0.5803,  ...,  0.9528, -1.9844, -1.9844],
         [ 0.1620, -0.2899, -1.5970,  ...,  0.7591, -1.9844, -1.9844],
         [ 0.4041, -0.4674, -1.9037,  ...,  0.2588, -1.9844, -1.9844]],

        [[-1.7107, -1.7107, -1.7107,  ..., -1.7107, -1.7107, -1.7107],
         [-0.0880, -0.1481, -0.1782,  ..., -0

In [51]:
mine[0]-sys[0]

tensor([[[-6.0989e+01, -4.4989e+01, -5.1989e+01,  ..., -1.5999e+02,
          -1.5399e+02, -1.4999e+02],
         [-1.5481e+01,  5.1906e-01, -1.7465e+01,  ..., -1.2405e+02,
          -1.2099e+02, -1.2399e+02],
         [-2.5037e+01, -1.5878e+01, -4.8878e+01,  ..., -1.1974e+02,
          -1.2199e+02, -1.1099e+02],
         ...,
         [-2.0724e+02, -2.0004e+02, -1.9818e+02,  ..., -1.5850e+02,
          -5.7989e+01, -5.4989e+01],
         [-1.7945e+02, -1.7281e+02, -1.8720e+02,  ..., -1.8269e+02,
          -9.8989e+01, -8.4989e+01],
         [-1.7607e+02, -1.6791e+02, -1.8045e+02,  ..., -2.1513e+02,
          -1.5299e+02, -1.2499e+02]],

        [[-6.3984e+01, -4.7984e+01, -4.9984e+01,  ..., -1.3398e+02,
          -1.2698e+02, -1.2598e+02],
         [-1.9854e+01,  1.1360e-01, -7.9025e+00,  ..., -8.8984e+01,
          -8.4984e+01, -8.8984e+01],
         [-2.4564e+01, -7.4351e+00, -2.7467e+01,  ..., -8.5662e+01,
          -8.5984e+01, -7.4984e+01],
         ...,
         [-1.6966e+02, -1

In [2]:
import numpy

In [5]:
m=numpy.random.random((3,4,5,5))

In [9]:
m[:,:,::2,::2]

array([[[[0.01946144, 0.3837943 , 0.00601776],
         [0.01611968, 0.98352235, 0.15981425],
         [0.5220738 , 0.64565804, 0.32935976]],

        [[0.43645331, 0.91359925, 0.01248987],
         [0.94457551, 0.08596305, 0.67231564],
         [0.21821406, 0.32676167, 0.10771398]],

        [[0.23623151, 0.19434949, 0.35754491],
         [0.14307982, 0.25360748, 0.01828019],
         [0.36337494, 0.03569094, 0.46626495]],

        [[0.67666238, 0.93079864, 0.37200043],
         [0.81023321, 0.99900131, 0.95404536],
         [0.37284265, 0.60932699, 0.79180186]]],


       [[[0.83324954, 0.38184331, 0.37697222],
         [0.30820563, 0.11552529, 0.5608663 ],
         [0.57890665, 0.60528553, 0.62793589]],

        [[0.95209835, 0.61594898, 0.62651286],
         [0.93137064, 0.33972718, 0.86130307],
         [0.58192237, 0.78244961, 0.27880706]],

        [[0.44293021, 0.75845853, 0.00964125],
         [0.42220947, 0.29116435, 0.17445362],
         [0.02391337, 0.63534818, 0.5431236 ]]

In [24]:
import sys


In [25]:
a=[]
b=a
print(sys.getrefcount(a))

3


In [26]:
print(sys.getrefcount(b))


3


In [28]:
c=[]
print(sys.getrefcount(a))
print(sys.getrefcount(c))


a.clear()
print(sys.getrefcount(a))
print(id(b))

b=c
print(sys.getrefcount(a))
print(sys.getrefcount(c))
print(sys.getrefcount(b))
print(id(b))
b=a
del a
print(sys.getrefcount(b))
print(id(b))


NameError: name 'a' is not defined